### ISSUE TITLE
Getting errors while compiling | How to compile properly?

### ISSUE THREAD

**Issue by fus0g** [Giuliano69/uvc_driver-for-Quanta-HD-User-Facing-0x0408-0x4035-#1]
**I am compiling on pop os 22.04 using the compile_module.sh and getting these errors**

`/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:42:31: error: array type has incomplete element type ‘struct uvc_format_desc’
   42 | static struct uvc_format_desc uvc_fmts[] = {
      |                               ^~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:45:35: error: ‘UVC_GUID_FORMAT_YUY2’ undeclared here (not in a function)
   45 |                 .guid           = UVC_GUID_FORMAT_YUY2,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:50:35: error: ‘UVC_GUID_FORMAT_YUY2_ISIGHT’ undeclared here (not in a function)
   50 |                 .guid           = UVC_GUID_FORMAT_YUY2_ISIGHT,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:55:35: error: ‘UVC_GUID_FORMAT_NV12’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
   55 |                 .guid           = UVC_GUID_FORMAT_NV12,
      |                                   ^~~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:60:35: error: ‘UVC_GUID_FORMAT_MJPEG’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_MJPEG’?
   60 |                 .guid           = UVC_GUID_FORMAT_MJPEG,
      |                                   ^~~~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_MJPEG
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:65:35: error: ‘UVC_GUID_FORMAT_YV12’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
   65 |                 .guid           = UVC_GUID_FORMAT_YV12,
      |                                   ^~~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:70:35: error: ‘UVC_GUID_FORMAT_I420’ undeclared here (not in a function)
   70 |                 .guid           = UVC_GUID_FORMAT_I420,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:75:35: error: ‘UVC_GUID_FORMAT_M420’ undeclared here (not in a function)
   75 |                 .guid           = UVC_GUID_FORMAT_M420,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:80:35: error: ‘UVC_GUID_FORMAT_UYVY’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
   80 |                 .guid           = UVC_GUID_FORMAT_UYVY,
      |                                   ^~~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:85:35: error: ‘UVC_GUID_FORMAT_Y800’ undeclared here (not in a function)
   85 |                 .guid           = UVC_GUID_FORMAT_Y800,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:90:35: error: ‘UVC_GUID_FORMAT_Y8’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
   90 |                 .guid           = UVC_GUID_FORMAT_Y8,
      |                                   ^~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:95:35: error: ‘UVC_GUID_FORMAT_D3DFMT_L8’ undeclared here (not in a function)
   95 |                 .guid           = UVC_GUID_FORMAT_D3DFMT_L8,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:100:35: error: ‘UVC_GUID_FORMAT_KSMEDIA_L8_IR’ undeclared here (not in a function)
  100 |                 .guid           = UVC_GUID_FORMAT_KSMEDIA_L8_IR,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:105:35: error: ‘UVC_GUID_FORMAT_Y10’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
  105 |                 .guid           = UVC_GUID_FORMAT_Y10,
      |                                   ^~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:110:35: error: ‘UVC_GUID_FORMAT_Y12’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
  110 |                 .guid           = UVC_GUID_FORMAT_Y12,
      |                                   ^~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:115:35: error: ‘UVC_GUID_FORMAT_Y16’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
  115 |                 .guid           = UVC_GUID_FORMAT_Y16,
      |                                   ^~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:120:35: error: ‘UVC_GUID_FORMAT_BY8’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
  120 |                 .guid           = UVC_GUID_FORMAT_BY8,
      |                                   ^~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:125:35: error: ‘UVC_GUID_FORMAT_BA81’ undeclared here (not in a function)
  125 |                 .guid           = UVC_GUID_FORMAT_BA81,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:130:35: error: ‘UVC_GUID_FORMAT_GBRG’ undeclared here (not in a function)
  130 |                 .guid           = UVC_GUID_FORMAT_GBRG,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:135:35: error: ‘UVC_GUID_FORMAT_GRBG’ undeclared here (not in a function)
  135 |                 .guid           = UVC_GUID_FORMAT_GRBG,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:140:35: error: ‘UVC_GUID_FORMAT_RGGB’ undeclared here (not in a function)
  140 |                 .guid           = UVC_GUID_FORMAT_RGGB,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:145:35: error: ‘UVC_GUID_FORMAT_RGBP’ undeclared here (not in a function)
  145 |                 .guid           = UVC_GUID_FORMAT_RGBP,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:150:35: error: ‘UVC_GUID_FORMAT_BGR3’ undeclared here (not in a function)
  150 |                 .guid           = UVC_GUID_FORMAT_BGR3,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:155:35: error: ‘UVC_GUID_FORMAT_H264’ undeclared here (not in a function)
  155 |                 .guid           = UVC_GUID_FORMAT_H264,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:160:35: error: ‘UVC_GUID_FORMAT_Y8I’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
  160 |                 .guid           = UVC_GUID_FORMAT_Y8I,
      |                                   ^~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:165:35: error: ‘UVC_GUID_FORMAT_Y12I’ undeclared here (not in a function)
  165 |                 .guid           = UVC_GUID_FORMAT_Y12I,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:170:35: error: ‘UVC_GUID_FORMAT_Z16’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
  170 |                 .guid           = UVC_GUID_FORMAT_Z16,
      |                                   ^~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:175:35: error: ‘UVC_GUID_FORMAT_RW10’ undeclared here (not in a function)
  175 |                 .guid           = UVC_GUID_FORMAT_RW10,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:180:35: error: ‘UVC_GUID_FORMAT_BG16’ undeclared here (not in a function)
  180 |                 .guid           = UVC_GUID_FORMAT_BG16,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:185:35: error: ‘UVC_GUID_FORMAT_GB16’ undeclared here (not in a function)
  185 |                 .guid           = UVC_GUID_FORMAT_GB16,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:190:35: error: ‘UVC_GUID_FORMAT_RG16’ undeclared here (not in a function)
  190 |                 .guid           = UVC_GUID_FORMAT_RG16,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:195:35: error: ‘UVC_GUID_FORMAT_GR16’ undeclared here (not in a function)
  195 |                 .guid           = UVC_GUID_FORMAT_GR16,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:200:35: error: ‘UVC_GUID_FORMAT_INVZ’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
  200 |                 .guid           = UVC_GUID_FORMAT_INVZ,
      |                                   ^~~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:205:35: error: ‘UVC_GUID_FORMAT_INVI’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
  205 |                 .guid           = UVC_GUID_FORMAT_INVI,
      |                                   ^~~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:210:35: error: ‘UVC_GUID_FORMAT_INZI’ undeclared here (not in a function)
  210 |                 .guid           = UVC_GUID_FORMAT_INZI,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:215:35: error: ‘UVC_GUID_FORMAT_CNF4’ undeclared here (not in a function)
  215 |                 .guid           = UVC_GUID_FORMAT_CNF4,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:220:35: error: ‘UVC_GUID_FORMAT_HEVC’ undeclared here (not in a function); did you mean ‘UVC_VS_FORMAT_DV’?
  220 |                 .guid           = UVC_GUID_FORMAT_HEVC,
      |                                   ^~~~~~~~~~~~~~~~~~~~
      |                                   UVC_VS_FORMAT_DV
In file included from ./include/linux/atomic/atomic-instrumented.h:20,
                 from ./include/linux/atomic.h:82,
                 from /home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:9:
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c: In function ‘uvc_format_by_guid’:
./include/linux/build_bug.h:16:51: error: bit-field ‘<anonymous>’ width not an integer constant
   16 | #define BUILD_BUG_ON_ZERO(e) ((int)(sizeof(struct { int:(-!!(e)); })))
      |                                                   ^
./include/linux/compiler.h:232:33: note: in expansion of macro ‘BUILD_BUG_ON_ZERO’
  232 | #define __must_be_array(a)      BUILD_BUG_ON_ZERO(__same_type((a), &(a)[0]))
      |                                 ^~~~~~~~~~~~~~~~~
./include/linux/kernel.h:55:59: note: in expansion of macro ‘__must_be_array’
   55 | #define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]) + __must_be_array(arr))
      |                                                           ^~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:246:28: note: in expansion of macro ‘ARRAY_SIZE’
  246 |         unsigned int len = ARRAY_SIZE(uvc_fmts);
      |                            ^~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c: In function ‘uvc_parse_format’:
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:534:39: error: ‘struct uvc_format’ has no member named ‘name’
  534 |                         strscpy(format->name, fmtdesc->name,
      |                                       ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:534:54: error: invalid use of undefined type ‘struct uvc_format_desc’
  534 |                         strscpy(format->name, fmtdesc->name,
      |                                                      ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:535:46: error: ‘struct uvc_format’ has no member named ‘name’
  535 |                                 sizeof(format->name));
      |                                              ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:536:46: error: invalid use of undefined type ‘struct uvc_format_desc’
  536 |                         format->fcc = fmtdesc->fcc;
      |                                              ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:540:40: error: ‘struct uvc_format’ has no member named ‘name’
  540 |                         snprintf(format->name, sizeof(format->name), "%pUl\n",
      |                                        ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:540:61: error: ‘struct uvc_format’ has no member named ‘name’
  540 |                         snprintf(format->name, sizeof(format->name), "%pUl\n",
      |                                                             ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:552:47: error: ‘struct uvc_format’ has no member named ‘name’
  552 |                                 strscpy(format->name, "Greyscale 8-bit (Y8  )",
      |                                               ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:553:54: error: ‘struct uvc_format’ has no member named ‘name’
  553 |                                         sizeof(format->name));
      |                                                      ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:594:31: error: ‘struct uvc_format’ has no member named ‘name’
  594 |                 strscpy(format->name, "MJPEG", sizeof(format->name));
      |                               ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:594:61: error: ‘struct uvc_format’ has no member named ‘name’
  594 |                 strscpy(format->name, "MJPEG", sizeof(format->name));
      |                                                             ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:612:39: error: ‘struct uvc_format’ has no member named ‘name’
  612 |                         strscpy(format->name, "SD-DV", sizeof(format->name));
      |                                       ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:612:69: error: ‘struct uvc_format’ has no member named ‘name’
  612 |                         strscpy(format->name, "SD-DV", sizeof(format->name));
      |                                                                     ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:615:39: error: ‘struct uvc_format’ has no member named ‘name’
  615 |                         strscpy(format->name, "SDL-DV", sizeof(format->name));
      |                                       ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:615:70: error: ‘struct uvc_format’ has no member named ‘name’
  615 |                         strscpy(format->name, "SDL-DV", sizeof(format->name));
      |                                                                      ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:618:39: error: ‘struct uvc_format’ has no member named ‘name’
  618 |                         strscpy(format->name, "HD-DV", sizeof(format->name));
      |                                       ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:618:69: error: ‘struct uvc_format’ has no member named ‘name’
  618 |                         strscpy(format->name, "HD-DV", sizeof(format->name));
      |                                                                     ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:628:31: error: ‘struct uvc_format’ has no member named ‘name’
  628 |                 strlcat(format->name, buffer[8] & (1 << 7) ? " 60Hz" : " 50Hz",
      |                               ^~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:629:38: error: ‘struct uvc_format’ has no member named ‘name’
  629 |                         sizeof(format->name));
      |                                      ^~
In file included from ./include/linux/device.h:15,
                 from ./include/linux/usb.h:19,
                 from /home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:15:
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:657:56: error: ‘struct uvc_format’ has no member named ‘name’
  657 |         uvc_dbg(dev, DESCR, "Found format %s\n", format->name);
      |                                                        ^~
./include/linux/dev_printk.h:129:48: note: in definition of macro ‘dev_printk’
  129 |                 _dev_printk(level, dev, fmt, ##__VA_ARGS__);            \
      |                                                ^~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:657:9: note: in expansion of macro ‘uvc_dbg’
  657 |         uvc_dbg(dev, DESCR, "Found format %s\n", format->name);
      |         ^~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c: At top level:
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:1027:39: error: ‘UVC_GUID_UVC_CAMERA’ undeclared here (not in a function); did you mean ‘UVC_ITT_CAMERA’?
 1027 | static const u8 uvc_camera_guid[16] = UVC_GUID_UVC_CAMERA;
      |                                       ^~~~~~~~~~~~~~~~~~~
      |                                       UVC_ITT_CAMERA
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:1028:37: error: ‘UVC_GUID_EXT_GPIO_CONTROLLER’ undeclared here (not in a function)
 1028 | static const u8 uvc_gpio_guid[16] = UVC_GUID_EXT_GPIO_CONTROLLER;
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:1030:9: error: ‘UVC_GUID_UVC_MEDIA_TRANSPORT_INPUT’ undeclared here (not in a function); did you mean ‘UVC_ITT_MEDIA_TRANSPORT_INPUT’?
 1030 |         UVC_GUID_UVC_MEDIA_TRANSPORT_INPUT;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         UVC_ITT_MEDIA_TRANSPORT_INPUT
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:1031:43: error: ‘UVC_GUID_UVC_PROCESSING’ undeclared here (not in a function)
 1031 | static const u8 uvc_processing_guid[16] = UVC_GUID_UVC_PROCESSING;
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~
/home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.c:42:31: warning: ‘uvc_fmts’ defined but not used [-Wunused-variable]
   42 | static struct uvc_format_desc uvc_fmts[] = {
      |                               ^~~~~~~~
make[1]: *** [scripts/Makefile.build:252: /home/proxxy/linux-6.2.6/drivers/media/usb/uvc/uvc_driver.o] Error 1
make: *** [Makefile:2021: /home/proxxy/linux-6.2.6/drivers/media/usb/uvc] Error 2
make: Leaving directory '/usr/src/linux-headers-6.2.6-76060206-generic'
`

**Comment by TheAthleticCoder** [comment]
Hey, were you able to resolve this?

**Comment by TheAthleticCoder** [comment]
@PrabhatProxy @Giuliano69

**Comment by fus0g** [comment]
@TheAthleticCoder  Not Yet

**Comment by Killgore87** [comment]
+1 waiting for resolve this problem for kernel 6.4

**Comment by takshakmudgal** [comment]
Petition for the dev, to add a READEME.md with step-by-step installation guide, if possible.

**Comment by romainwg** [comment]
> Petition for the dev, to add a READEME.md with step-by-step installation guide, if possible.

I did it on a fork: https://github.com/romainwg/uvc_driver-for-Quanta-HD-User-Facing-0x0408-0x4035-

**Comment by gab-aquino** [comment]
> > Petition for the dev, to add a READEME.md with step-by-step installation guide, if possible.
> 
> I did it on a fork: https://github.com/romainwg/uvc_driver-for-Quanta-HD-User-Facing-0x0408-0x4035-

Thanks for providing this. For some reason it didn't worked for me using your `compile_module.sh`, I've used [REASY sh instead that you mentioned](https://github.com/Giuliano69/uvc_driver-for-Quanta-HD-User-Facing-0x0408-0x4035-/issues/3#issuecomment-1715009720) and it worked. Although, I couldn't find any significant difference between you guys files.

Thanks once again.

**Comment by TheAthleticCoder** [comment]
@romainwg 
Does this fork only work for Ubuntu 22.04?  I am using a Ubuntu 23.10
It would be really helpful to know if there are any changes I can make such that it runs on my version as well.

**Comment by fus0g** [comment]
@TheAthleticCoder fixed it in my repo > https://github.com/PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux
