### ISSUE TITLE
Compilation Terminated in Kernel 6.5.0-14-generic (Ubuntu 22.04.3 LTS)

### ISSUE THREAD

**Issue by ghost** [Giuliano69/uvc_driver-for-Quanta-HD-User-Facing-0x0408-0x4035-#4]
make -j4 -C /lib/modules/$(uname -r)/build M=$(pwd) modules                                                                  
make: Entering directory '/usr/src/linux-headers-6.5.0-14-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  ^~ You are using: gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  CC [M]  /home/vatsalya/camera-fix/linux-6.2/drivers/media/usb/uvc/uvc_driver.o
  CC [M]  /home/vatsalya/camera-fix/linux-6.2/drivers/media/usb/uvc/uvc_queue.o
  CC [M]  /home/vatsalya/camera-fix/linux-6.2/drivers/media/usb/uvc/uvc_v4l2.o
  CC [M]  /home/vatsalya/camera-fix/linux-6.2/drivers/media/usb/uvc/uvc_video.o
/home/vatsalya/camera-fix/linux-6.2/drivers/media/usb/uvc/uvc_driver.c:23:10: fatal error: media/v4l2-uvc.h: No such file or directory
   23 | #include <media/v4l2-uvc.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:251: /home/vatsalya/camera-fix/linux-6.2/drivers/media/usb/uvc/uvc_driver.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-headers-6.5.0-14-generic/Makefile:2037: /home/vatsalya/camera-fix/linux-6.2/drivers/media/usb/uvc] Error 2
make: *** [Makefile:234: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.5.0-14-generic'

**Comment by fus0g** [comment]
https://github.com/PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux

try this. Hopefully it would work

**Comment by ghost** [comment]
> https://github.com/PrabhatProxy/Quanta-HD-User-Facing-0x0408-0x4035_linux
> 
> try this. Hopefully it would work

Thank you very much. It worked on Fedora Workstation 39.

**Comment by PrabhatProxy** [comment]
@vatsalya-vyas don't forget to star my repo 😉
