### ISSUE TITLE
Help: How can I set up this driver on Arch Linux ?

### ISSUE THREAD

**Issue by tribhuwan-kumar** [Giuliano69/uvc_driver-for-Quanta-HD-User-Facing-0x0408-0x4035-#8]
[Here,](https://ubuntuforums.org/showthread.php?t=2477627&p=14147432#post14147432) you've instructed for setting up in Ubuntu. I tried to follow those steps in Arch Linux, but couldn't get work done! 
How can I set up this driver on Arch Linux ? 
This is my `lsusb` output:
```bash
 ~  lsusb | grep -i facing
Bus 003 Device 002: ID 0408:4033 Quanta Computer, Inc. ACER HD User Facing
```
Thanks for this driver, Sir!

**Comment by fus0g** [comment]
> [Here,](https://ubuntuforums.org/showthread.php?t=2477627&p=14147432#post14147432) you've instructed for setting up in Ubuntu. I tried to follow those steps in Arch Linux, but couldn't get work done! How can I set up this driver on Arch Linux ? This is my `lsusb` output:
> 
> ```shell
>  ~  lsusb | grep -i facing
> Bus 003 Device 002: ID 0408:4033 Quanta Computer, Inc. ACER HD User Facing
> ```
> 
> Thanks for this driver, Sir!

Use this https://github.com/fus0g/Quanta-HD-User-Facing-0x0408-0x4035_linux

**Comment by tribhuwan-kumar** [comment]
Thanks, It worked!!
